
# Startet denöffentlichen Proxy auf Port 80

version: '3.1'

services:
  streamer:
    build: "./streamer/."
    restart: always
    privileged: true
    volumes:
      -  "/lib/modules:/lib/modules:ro"

  controller:
    build: "./controller/."
    ports:
      - "81:81"
    #restart: always
    
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - streamer
      - controller
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./html:/usr/share/nginx/html:ro"

  ssh-server:
    depends_on:
      - nginx
      - streamer
    build: "./ssh-server/."
    restart: always
    ports:
      - "2200:22"
    volumes:
      - "./ssh-host-keys:/etc/ssh/ssh-host-keys"
      - "./ssh-authorized-keys:/etc/ssh/ssh-authorized-keys:ro"

